// Getters
export const CONTACTS_IS_LOADING = 'CONTACTS_IS_LOADING'
export const CONTACTS_LIST = 'CONTACTS_LIST'
export const CONTACTS_DETAIL = 'CONTACTS_DETAIL'
export const CONTACTS_ERRORS = 'CONTACTS_ERRORS'

// Mutations
export const CONTACTS_SET_IS_LOADING = 'CONTACTS_SET_IS_LOADING'
export const CONTACTS_SET_LIST = 'CONTACTS_SET_LIST'
export const CONTACTS_SET_DETAIL = 'CONTACTS_SET_DETAIL'
export const CONTACTS_SET_ERRORS = 'CONTACTS_SET_ERRORS'

// Actions
export const CONTACTS_GET_LIST = 'CONTACTS_GET_LIST'
export const CONTACTS_GET_DETAIL = 'CONTACTS_GET_DETAIL'
export const CONTACTS_CREATE = 'CONTACTS_CREATE'
export const CONTACTS_DELETE = 'CONTACTS_DELETE'
export const CONTACTS_DELETE_ALL = 'CONTACTS_DELETE_ALL'
